// @flow strict
export type GalleryItemDetailed = { [key: string]: mixed };
export type GalleryItemSummary = { [key: string]: mixed };
export type GalleryItemCustom = { [key: string]: mixed };
export type PinDetailed = {|
  id?: string,
  type?: string,
  access?: Array<string>,
  activity?: ?number,
  ad_destination_url?: ?string,
  ad_match_reason?: ?number,
  ad_targeting_attribution?: {| [key: string]: mixed |},
  additional_hide_reasons?: Array<number>,
  attribution?: ?{| [key: string]: mixed |},
  cacheable_id?: string,
  can_delete_did_it_and_comments?: boolean,
  category?: ?string,
  category_p2i?: ?number,
  click_through_link_quality?: ?{| [key: string]: mixed |},
  client_id?: ?string,
  closeup_description?: ?string,
  closeup_unified_title?: ?string,
  closeup_unified_description?: ?string,
  closeup_user_note?: ?string,
  comment_count?: number,
  comments_disabled?: boolean,
  content_sensitivity?: {| [key: string]: mixed |},
  created_at?: ?string,
  cta_text?: ?string,
  dark_profile_link?: string,
  description?: ?string,
  destination_url_type?: ?number,
  did_it_disabled?: boolean,
  domain?: string,
  domain_tracking_params?:
    | Array<number>
    | Array<string>
    | Array<{| [key: string]: mixed |}>
    | Array<boolean>
    | Array<number>
    | Array<Array<mixed>>,
  dominant_color?: ?string,
  done_by_board_contributors?: boolean,
  edited_fields?: Array<string>,
  embed?: ?{| [key: string]: mixed |},
  feedback_options?: ?{| [key: string]: mixed |},
  debug_info_html?: ?string,
  grid_description?: ?string,
  grid_title?: string,
  grid_title_ads_experiment?: string,
  has_been_promoted?: boolean,
  has_required_attribution_provider?: boolean,
  hashtags?: Array<string>,
  headline_text?: string,
  image_signature?: string,
  image_square_url?: ?string,
  image_square_size_pixels?: ?{| [key: string]: mixed |},
  image_square_size_points?: ?{| [key: string]: mixed |},
  image_medium_url?: ?string,
  image_medium_size_pixels?: ?{| [key: string]: mixed |},
  image_medium_size_points?: ?{| [key: string]: mixed |},
  image_large_url?: ?string,
  image_large_size_pixels?: ?{| [key: string]: mixed |},
  image_large_size_points?: ?{| [key: string]: mixed |},
  image_did_it_count?: ?number,
  is_blocked?: boolean,
  is_cpc_ad?: boolean,
  is_playable?: boolean,
  is_promoted?: boolean,
  is_eligible_for_cta?: boolean,
  is_eligible_for_web_closeup?: boolean,
  is_eligible_for_brand_catalog?: boolean,
  is_oos_product?: boolean,
  is_stale_product?: boolean,
  is_downstream_promotion?: boolean,
  is_full_width?: boolean,
  is_ghost?: boolean,
  is_hidden?: boolean,
  is_prefetch_enabled?: ?boolean,
  is_porn_domain?: boolean,
  is_repin?: boolean,
  is_scene?: boolean,
  is_shopping_ad?: boolean,
  is_spam_domain?: boolean,
  is_best_tried_it?: ?boolean,
  is_uploaded?: boolean,
  is_video?: boolean,
  is_quick_promotable?: boolean,
  is_quick_promotable_by_pinner?: boolean,
  is_whitelisted_for_tried_it?: boolean,
  link?: ?string,
  price_currency?: string,
  price_value?: number,
  repin_count?: number,
  title?: ?string,
  tracked_link?: ?string,
  tracking_params?: ?string,
  is_promotable?: ?boolean,
  is_native?: ?boolean,
|};
export type PinSummary = {|
  id?: string,
  type?: string,
  attribution?: ?{| [key: string]: mixed |},
  cacheable_id?: string,
  comment_count?: number,
  created_at?: ?string,
  description?: ?string,
  domain?: string,
  image_square_url?: ?string,
  image_square_size_pixels?: ?{| [key: string]: mixed |},
  image_square_size_points?: ?{| [key: string]: mixed |},
  image_medium_url?: ?string,
  image_medium_size_pixels?: ?{| [key: string]: mixed |},
  image_medium_size_points?: ?{| [key: string]: mixed |},
  image_large_url?: ?string,
  image_large_size_pixels?: ?{| [key: string]: mixed |},
  image_large_size_points?: ?{| [key: string]: mixed |},
  is_playable?: boolean,
  is_downstream_promotion?: boolean,
  is_repin?: boolean,
  is_uploaded?: boolean,
  is_video?: boolean,
  link?: ?string,
  price_currency?: string,
  price_value?: number,
  repin_count?: number,
  title?: ?string,
  tracked_link?: ?string,
  tracking_params?: ?string,
|};
export type PinCustom = {|
  id?: string,
  type?: string,
  access?: Array<string>,
  activity?: ?number,
  ad_destination_url?: ?string,
  ad_match_reason?: ?number,
  ad_targeting_attribution?: {| [key: string]: mixed |},
  additional_hide_reasons?: Array<number>,
  attribution?: ?{| [key: string]: mixed |},
  cacheable_id?: string,
  can_delete_did_it_and_comments?: boolean,
  category?: ?string,
  category_p2i?: ?number,
  cinematic_data?: {| [key: string]: mixed |},
  click_through_action?: number,
  click_through_link_quality?: ?{| [key: string]: mixed |},
  client_id?: ?string,
  closeup_description?: ?string,
  closeup_unified_title?: ?string,
  closeup_unified_description?: ?string,
  closeup_user_note?: ?string,
  comment_count?: number,
  comments_disabled?: boolean,
  content_sensitivity?: {| [key: string]: mixed |},
  created_at?: ?string,
  creative_types?: ?Array<string>,
  cta_text?: ?string,
  dark_profile_link?: string,
  description?: ?string,
  description_html?: string,
  destination_url_type?: ?number,
  did_it_disabled?: boolean,
  domain?: string,
  domain_tracking_params?:
    | Array<number>
    | Array<string>
    | Array<{| [key: string]: mixed |}>
    | Array<boolean>
    | Array<number>
    | Array<Array<mixed>>,
  dominant_color?: ?string,
  done_by_me?: boolean,
  done_by_board_contributors?: boolean,
  edited_fields?: Array<string>,
  embed?: ?{| [key: string]: mixed |},
  feedback_options?: ?{| [key: string]: mixed |},
  gallery?: {| [key: string]: mixed |},
  debug_info_html?: ?string,
  upsell_audience_size?: ?{| [key: string]: mixed |},
  grid_description?: ?string,
  grid_title?: string,
  grid_title_ads_experiment?: string,
  has_been_promoted?: boolean,
  has_required_attribution_provider?: boolean,
  hashtags?: Array<string>,
  headline_text?: string,
  image_signature?: string,
  image_square_url?: ?string,
  image_square_size_pixels?: ?{| [key: string]: mixed |},
  image_square_size_points?: ?{| [key: string]: mixed |},
  image_medium_url?: ?string,
  image_medium_size_pixels?: ?{| [key: string]: mixed |},
  image_medium_size_points?: ?{| [key: string]: mixed |},
  image_large_url?: ?string,
  image_large_size_pixels?: ?{| [key: string]: mixed |},
  image_large_size_points?: ?{| [key: string]: mixed |},
  images?: {| [key: string]: mixed |},
  has_bad_category?: ?boolean,
  has_male_category?: ?boolean,
  image_did_it_count?: ?number,
  is_blocked?: boolean,
  is_cinematic?: boolean,
  is_cpc_ad?: boolean,
  is_playable?: boolean,
  is_promoted?: boolean,
  is_eligible_for_aggregated_comments?: boolean,
  is_eligible_for_cta?: boolean,
  is_eligible_for_web_closeup?: boolean,
  is_eligible_for_brand_catalog?: boolean,
  is_eligible_for_responses?: boolean,
  is_eligible_for_stela_categories?: boolean,
  is_eligible_for_flashlight_shopping?: boolean,
  is_eligible_for_reverse_stela?: boolean,
  is_eligible_for_related_products?: boolean,
  is_eligible_for_pdp?: boolean,
  is_oos_product?: boolean,
  is_stale_product?: boolean,
  is_downstream_promotion?: boolean,
  is_full_width?: boolean,
  is_ghost?: boolean,
  is_hidden?: boolean,
  is_native_video?: ?boolean,
  is_prefetch_enabled?: ?boolean,
  is_porn_domain?: boolean,
  is_post_reranked?: boolean,
  is_repin?: boolean,
  is_scene?: boolean,
  is_shopping_ad?: boolean,
  is_spam_domain?: boolean,
  is_best_tried_it?: ?boolean,
  is_uploaded?: boolean,
  is_video?: boolean,
  is_virtual_try_on?: boolean,
  is_quick_promotable?: boolean,
  is_quick_promotable_by_pinner?: boolean,
  is_whitelisted_for_tried_it?: boolean,
  link?: ?string,
  price_currency?: string,
  price_value?: number,
  repin_count?: number,
  title?: ?string,
  tracked_link?: ?string,
  tracking_params?: ?string,
  is_promotable?: ?boolean,
  is_native?: ?boolean,
|};
export type BoardActionLockDetailed = {| is_origin?: ?boolean |};
export type BoardActionLockSummary = {| is_origin?: ?boolean |};
export type BoardActionLockCustom = {| is_origin?: ?boolean |};
export type CollaboratorInviteDetailed = {| is_acceptable?: ?boolean |};
export type CollaboratorInviteSummary = {| is_acceptable?: ?boolean |};
export type CollaboratorInviteCustom = {| is_acceptable?: ?boolean |};
export type PinTypeFilterDetailed = {|
  id?: string,
  type?: string,
  pin_type?: number,
  text?: string,
|};
export type PinTypeFilterSummary = {|
  id?: string,
  type?: string,
  pin_type?: number,
  text?: string,
|};
export type PinTypeFilterCustom = {|
  id?: string,
  type?: string,
  pin_type?: number,
  text?: string,
|};
export type BoardDetailed = {|
  id?: string,
  type?: string,
  access?: Array<string>,
  allow_homefeed_recommendations?: boolean,
  board_activity_count?: number,
  board_order_modified_at?: ?string,
  category?: ?string,
  collab_board_email?: boolean,
  collaborated_by_me?: boolean,
  collaborator_count?: number,
  collaborator_invites_enabled?: boolean,
  collaborator_requests_enabled?: boolean,
  created_at?: ?string,
  debug?: ?string,
  description?: ?string,
  event_date?: ?string,
  event_start_date?: ?string,
  followed_by_me?: boolean,
  follower_count?: number,
  has_pending_invite?: boolean,
  ideas_url?: string,
  image_cover_hd_url?: ?string,
  image_cover_url?: ?string,
  image_thumbnail_url?: string,
  image_thumbnail_urls?: ?{| [key: string]: mixed |},
  images?: ?{| [key: string]: mixed |},
  is_collaborative?: boolean,
  is_eligible_for_seasonal_share_treatment?: boolean,
  layout?: string,
  map_id?: string,
  name?: string,
  pin_count?: number,
  predicted_category?: ?string,
  privacy?: string,
  recommendation_reason?: ?string,
  should_show_board_activity?: boolean,
  should_show_shop_feed?: boolean,
  topic?: ?string,
  url?: string,
  viewer_collaborator_join_requested?: boolean,
  viewer_invitation?: ?{| [key: string]: mixed |},
  board_note_count?: ?number,
  collaborator_permissions?: Array<number>,
  collaborator_permissions_setting?: number,
|};
export type BoardSummary = {|
  id?: string,
  type?: string,
  board_order_modified_at?: ?string,
  category?: ?string,
  collaborated_by_me?: boolean,
  created_at?: ?string,
  followed_by_me?: boolean,
  image_thumbnail_url?: string,
  is_collaborative?: boolean,
  layout?: string,
  name?: string,
  url?: string,
|};
export type BoardCustom = {|
  id?: string,
  type?: string,
  access?: Array<string>,
  allow_homefeed_recommendations?: boolean,
  annotations?: ?Array<string>,
  archived_by_me_at?: ?string,
  blocking_actions?: Array<
    BoardActionLockCustom | BoardActionLockDetailed | BoardActionLockSummary
  >,
  board_activity_count?: number,
  board_order_modified_at?: ?string,
  board_owner_has_active_ads?: boolean,
  category?: ?string,
  collab_board_email?: boolean,
  collaborated_by_me?: boolean,
  collaborator_count?: number,
  collaborator_invites_enabled?: boolean,
  collaborator_requests_enabled?: boolean,
  cover_images?: ?{| [key: string]: mixed |},
  cover_pin?: ?{| [key: string]: mixed |},
  created_at?: ?string,
  debug?: ?string,
  description?: ?string,
  event_date?: ?string,
  event_start_date?: ?string,
  followed_by_me?: boolean,
  follower_count?: number,
  has_active_ads?: boolean,
  has_custom_cover?: boolean,
  has_fresh_more_ideas_tab?: boolean,
  has_new_activity?: boolean,
  has_pending_invite?: boolean,
  ideas_deep_link_url?: string,
  ideas_url?: string,
  image_cover_hd_url?: ?string,
  image_cover_url?: ?string,
  image_thumbnail_url?: string,
  image_thumbnail_urls?: ?{| [key: string]: mixed |},
  images?: ?{| [key: string]: mixed |},
  is_collaborative?: boolean,
  is_eligible_for_homefeed_tabs?: boolean,
  is_eligible_for_seasonal_share_treatment?: boolean,
  layout?: string,
  map_id?: string,
  name?: string,
  pin_count?: number,
  places_enabled?: boolean,
  predicted_category?: ?string,
  privacy?: string,
  protected?: boolean,
  recommendation_reason?: ?string,
  section_count?: number,
  sectionless_pin_count?: number,
  should_show_board_activity?: boolean,
  should_show_more_ideas?: boolean,
  should_show_shop_feed?: boolean,
  topic?: ?string,
  url?: string,
  viewer_collaborator_join_requested?: boolean,
  viewer_invitation?: ?{| [key: string]: mixed |},
  place_recs_count?: number,
  place_saves_count?: number,
  board_note_count?: ?number,
  collaborator_permissions?: Array<number>,
  collaborator_permissions_setting?: number,
  eligible_pin_type_filters?: Array<
    PinTypeFilterCustom | PinTypeFilterDetailed | PinTypeFilterSummary
  >,
|};
export type UserDetailed = {|
  id?: string,
  type?: string,
  about?: string,
  board_count?: number,
  group_board_count?: number,
  domain_url?: ?string,
  domain_verified?: boolean,
  followed_by_me?: boolean,
  follower_count?: number,
  following_count?: number,
  impressum_url?: ?string,
  is_any_website_verified?: boolean,
  is_default_image?: boolean,
  is_partner?: boolean,
  is_verified_merchant?: boolean,
  is_primary_website_verified?: boolean,
  like_count?: number,
  location?: ?string,
  merchant_id?: string,
  pin_count?: number,
  pin_thumbnail_urls?: Array<string>,
  show_impressum?: boolean,
  recent_pin_images?: ?{| [key: string]: mixed |},
  username?: string,
  verified_domains?: Array<string>,
  verified_identity?: ?{| [key: string]: mixed |},
  verified_user_websites?: Array<string>,
  website_url?: ?string,
  listed_website_url?: ?string,
  profile_reach?: ?number,
  created_at?: string,
  first_name?: ?string,
  last_name?: ?string,
  full_name?: string,
  gender?: string,
  image_small_url?: string,
  image_medium_url?: string,
  image_large_url?: string,
  image_xlarge_url?: string,
  is_employee?: boolean,
  active?: boolean,
  debug?: {| [key: string]: mixed |},
  has_custom_board_sorting_order?: boolean,
  user_following_count?: number,
  last_login_country?: ?string,
  last_pin_like_time?: ?string,
  last_pin_save_time?: ?string,
  obfuscated_email?: string,
  native_pin_count?: number,
  pins_done_count?: number,
  profile_discovered_public?: boolean,
  recommendation_reason?: ?string,
  user_recommendation_reason?: ?{| [key: string]: mixed |},
  show_creator_profile?: boolean,
  show_discovered_feed?: boolean,
  tag?: ?string,
  blocked_by_me?: boolean,
  explicitly_followed_by_me?: boolean,
  implicitly_followed_by_me?: boolean,
  profile_cover_source?: ?string,
  canonical_merchant_domain?: ?string,
  commerce_module_data?: ?{| [key: string]: mixed |},
  is_geo_eligible_for_creator_messaging?: boolean,
  indexed?: boolean,
|};
export type UserSummary = {|
  id?: string,
  type?: string,
  username?: string,
  first_name?: ?string,
  last_name?: ?string,
  full_name?: string,
  gender?: string,
  image_small_url?: string,
  image_medium_url?: string,
  image_large_url?: string,
  image_xlarge_url?: string,
|};
export type UserCustom = {|
  id?: string,
  type?: string,
  about?: string,
  board_count?: number,
  browsing_level?: ?string,
  group_board_count?: number,
  domain_url?: ?string,
  domain_verified?: boolean,
  followed_by_me?: boolean,
  follower_count?: number,
  following_count?: number,
  impressum_url?: ?string,
  is_any_website_verified?: boolean,
  is_default_image?: boolean,
  is_partner?: boolean,
  is_verified_merchant?: boolean,
  is_primary_website_verified?: boolean,
  like_count?: number,
  location?: ?string,
  merchant_id?: string,
  pin_count?: number,
  pin_thumbnail_urls?: Array<string>,
  profile_url?: string,
  should_show_homefeed_ads?: boolean,
  show_impressum?: boolean,
  recent_pin_images?: ?{| [key: string]: mixed |},
  username?: string,
  verified_domains?: Array<string>,
  verified_identity?: ?{| [key: string]: mixed |},
  verified_user_websites?: Array<string>,
  website_url?: ?string,
  listed_website_url?: ?string,
  profile_reach?: ?number,
  ads_customize_from_conversion?: boolean,
  age_in_years?: number,
  allow_analytic_cookies?: boolean,
  allow_marketing_cookies?: boolean,
  allow_personalization_cookies?: boolean,
  archived_board_count?: number,
  can_enable_mfa?: boolean,
  ccpa_opted_out?: boolean,
  connected_to_facebook?: boolean,
  connected_to_google?: boolean,
  connected_to_gplus?: boolean,
  connected_to_instagram?: boolean,
  connected_to_old_instagram_auth?: boolean,
  connected_to_etsy?: boolean,
  connected_to_youtube?: boolean,
  connected_to_microsoft?: boolean,
  connected_to_rakuten?: boolean,
  connected_to_twitter?: boolean,
  connected_to_yahoo?: boolean,
  connected_to_dropbox?: boolean,
  custom_gender?: ?string,
  email?: ?string,
  exclude_from_search?: boolean,
  experiments?: {| [key: string]: mixed |},
  facebook_id?: ?string,
  facebook_publish_stream_enabled?: boolean,
  facebook_timeline_enabled?: boolean,
  has_content_claiming_access?: boolean,
  gatekeeper_experiments?: {| [key: string]: mixed |},
  has_mfa_enabled?: boolean,
  has_password?: boolean,
  has_seen_notifications?: boolean,
  is_high_risk?: boolean,
  is_write_banned?: boolean,
  is_third_party_ads_enabled?: boolean,
  login_state?: ?number,
  mfa_backup_codes?:
    | Array<number>
    | Array<string>
    | Array<{| [key: string]: mixed |}>
    | Array<boolean>
    | Array<number>
    | Array<Array<mixed>>,
  most_recent_board_sort_order?: string,
  nags?:
    | Array<number>
    | Array<string>
    | Array<{| [key: string]: mixed |}>
    | Array<boolean>
    | Array<number>
    | Array<Array<mixed>>,
  phone_country?: ?string,
  phone_number?: ?string,
  phone_number_end?: ?string,
  phone_number_without_country?: ?string,
  push_package_user_id?: string,
  scheduled_pin_count?: number,
  secret_board_count?: number,
  secret_boards_remaining?: number,
  third_party_ad_unit_id?: string,
  third_party_app_id?: string,
  third_party_ads_config?: {| [key: string]: mixed |},
  triggerable_experiments?: {| [key: string]: mixed |},
  twitter_publish_enabled?: boolean,
  unverified_phone_country?: ?string,
  unverified_phone_number?: ?string,
  unverified_phone_number_without_country?: ?string,
  resurrection_info?: ?{| [key: string]: mixed |},
  has_completed_quiz?: boolean,
  has_done_clickthrough?: boolean,
  has_done_closeup?: boolean,
  has_done_app_install?: boolean,
  personalize_from_offsite_browsing?: boolean,
  fast_advertiser_info_has_any_managed_advertisers?: boolean,
  ppa_merchant_id?: string,
  usmstate?: string,
  default_shipping?: ?{| [key: string]: mixed |},
  default_payment?: ?{| [key: string]: mixed |},
  facebook_url?: ?string,
  twitter_url?: ?string,
  gplus_url?: ?string,
  can_upload_cover?: boolean,
  video_upload_allowed?: boolean,
  ip_country?: ?string,
  third_party_marketing_tracking_enabled?: boolean,
  is_known_facebook_user?: boolean,
  created_at?: string,
  first_name?: ?string,
  last_name?: ?string,
  full_name?: string,
  gender?: string,
  image_small_url?: string,
  image_medium_url?: string,
  image_large_url?: string,
  image_xlarge_url?: string,
  is_employee?: boolean,
  active?: boolean,
  community_display_name?: string,
  community_role?: ?string,
  community_roles?:
    | Array<number>
    | Array<string>
    | Array<{| [key: string]: mixed |}>
    | Array<boolean>
    | Array<number>
    | Array<Array<mixed>>,
  debug?: {| [key: string]: mixed |},
  has_custom_board_sorting_order?: boolean,
  has_showcase?: boolean,
  has_shopping_showcase?: boolean,
  interest_following_count?: number,
  user_following_count?: number,
  explicit_user_following_count?: number,
  explicit_board_following_count?: number,
  is_tastemaker?: boolean,
  joined_communities_count?: number,
  last_login_country?: ?string,
  last_pin_done_time?: ?string,
  last_pin_like_time?: ?string,
  last_pin_save_time?: ?string,
  obfuscated_email?: string,
  native_pin_count?: number,
  pins_done_count?: number,
  has_catalog?: boolean,
  storefront_management_enabled?: boolean,
  storefront_search_enabled?: boolean,
  profile_discovered_public?: boolean,
  recommendation_reason?: ?string,
  user_recommendation_reason?: ?{| [key: string]: mixed |},
  show_creator_profile?: boolean,
  show_discovered_feed?: boolean,
  tag?: ?string,
  blocked_by_me?: boolean,
  explicitly_followed_by_me?: boolean,
  implicitly_followed_by_me?: boolean,
  eligible_profile_tabs?:
    | Array<number>
    | Array<string>
    | Array<{| [key: string]: mixed |}>
    | Array<boolean>
    | Array<number>
    | Array<Array<mixed>>,
  show_engagement_tab?: boolean,
  profile_cover_source?: ?string,
  canonical_merchant_domain?: ?string,
  commerce_module_data?: ?{| [key: string]: mixed |},
  is_geo_eligible_for_creator_messaging?: boolean,
  story_pin_count?: number,
  video_pin_count?: number,
  video_views?: number,
  indexed?: boolean,
  locale?: ?string,
  country?: ?string,
  is_eligible_for_shop_tab?: boolean,
|};
export type ResponseStatus = "success" | "failure";
export type ApiEnvelope = {|
  status: ResponseStatus,
  code: number,
  data:
    | number
    | string
    | {| [key: string]: mixed |}
    | boolean
    | number
    | Array<mixed>,
  message: string,
  endpoint_name: string,
  message_detail?: string,
  sensitivity?: {| [key: string]: mixed |},
  debug_logs?: Array<{| [key: string]: mixed |}>,
|};
export type ApiErrorEnvelope = {|
  status: ResponseStatus,
  code: number,
  data:
    | number
    | string
    | {| [key: string]: mixed |}
    | boolean
    | number
    | Array<mixed>,
  message: string,
  endpoint_name: string,
  message_detail?: string,
  sensitivity?: {| [key: string]: mixed |},
  debug_logs?: Array<{| [key: string]: mixed |}>,
  error?: {| [key: string]: mixed |},
|};
export type ApiBookmarkedEnvelope = {|
  status: ResponseStatus,
  code: number,
  data:
    | number
    | string
    | {| [key: string]: mixed |}
    | boolean
    | number
    | Array<mixed>,
  message: string,
  endpoint_name: string,
  message_detail?: string,
  sensitivity?: {| [key: string]: mixed |},
  debug_logs?: Array<{| [key: string]: mixed |}>,
  bookmark: string,
|};
export type fields = Array<string>;
export type add_fields = Array<string>;
export type base_scheme = "http" | "https";
export type render_style = "detailed" | "summary" | "all_fields";
