// @flow strict

export type ApiBookmarkedEnvelope = {|
  bookmark : string,
  code : number,
  data : | number
    | string
    | {| [key : string] : mixed |}
    | boolean
    | number
    | mixed[],
  debug_logs? : {| [key : string] : mixed |}[],
  endpoint_name : string,
  message : string,
  message_detail? : string,
  sensitivity? : {| [key : string] : mixed |},
  status : ResponseStatus,
|};
export type ApiEnvelope = {|
  code : number,
  data : | number
    | string
    | {| [key : string] : mixed |}
    | boolean
    | number
    | mixed[],
  debug_logs? : {| [key : string] : mixed |}[],
  endpoint_name : string,
  message : string,
  message_detail? : string,
  sensitivity? : {| [key : string] : mixed |},
  status : ResponseStatus,
|};
export type ApiErrorEnvelope = {|
  code : number,
  data : | number
    | string
    | {| [key : string] : mixed |}
    | boolean
    | number
    | mixed[],
  debug_logs? : {| [key : string] : mixed |}[],
  endpoint_name : string,
  error? : {| [key : string] : mixed |},
  message : string,
  message_detail? : string,
  sensitivity? : {| [key : string] : mixed |},
  status : ResponseStatus,
|};
export type ResponseStatus = "success" | "failure";
export type UserCustom = {|
  about? : string,
  active? : boolean,
  ads_customize_from_conversion? : boolean,
  age_in_years? : number,
  allow_analytic_cookies? : boolean,
  allow_marketing_cookies? : boolean,
  allow_personalization_cookies? : boolean,
  archived_board_count? : number,
  blocked_by_me? : boolean,
  board_count? : number,
  browsing_level? : ?string,
  can_enable_mfa? : boolean,
  can_upload_cover? : boolean,
  canonical_merchant_domain? : ?string,
  ccpa_opted_out? : boolean,
  commerce_module_data? : ?{| [key : string] : mixed |},
  community_display_name? : string,
  community_role? : ?string,
  community_roles? : | number[]
    | string[]
    | {| [key : string] : mixed |}[]
    | boolean[]
    | number[]
    | mixed[][],
  connected_to_dropbox? : boolean,
  connected_to_etsy? : boolean,
  connected_to_facebook? : boolean,
  connected_to_google? : boolean,
  connected_to_gplus? : boolean,
  connected_to_instagram? : boolean,
  connected_to_microsoft? : boolean,
  connected_to_old_instagram_auth? : boolean,
  connected_to_rakuten? : boolean,
  connected_to_twitter? : boolean,
  connected_to_yahoo? : boolean,
  connected_to_youtube? : boolean,
  country? : ?string,
  created_at? : string,
  custom_gender? : ?string,
  debug? : {| [key : string] : mixed |},
  default_payment? : ?{| [key : string] : mixed |},
  default_shipping? : ?{| [key : string] : mixed |},
  domain_url? : ?string,
  domain_verified? : boolean,
  eligible_profile_tabs? : | number[]
    | string[]
    | {| [key : string] : mixed |}[]
    | boolean[]
    | number[]
    | mixed[][],
  email? : ?string,
  exclude_from_search? : boolean,
  experiments? : {| [key : string] : mixed |},
  explicit_board_following_count? : number,
  explicit_user_following_count? : number,
  explicitly_followed_by_me? : boolean,
  facebook_id? : ?string,
  facebook_publish_stream_enabled? : boolean,
  facebook_timeline_enabled? : boolean,
  facebook_url? : ?string,
  fast_advertiser_info_has_any_managed_advertisers? : boolean,
  first_name? : ?string,
  followed_by_me? : boolean,
  follower_count? : number,
  following_count? : number,
  full_name? : string,
  gatekeeper_experiments? : {| [key : string] : mixed |},
  gender? : string,
  gplus_url? : ?string,
  group_board_count? : number,
  has_catalog? : boolean,
  has_completed_quiz? : boolean,
  has_content_claiming_access? : boolean,
  has_custom_board_sorting_order? : boolean,
  has_done_app_install? : boolean,
  has_done_clickthrough? : boolean,
  has_done_closeup? : boolean,
  has_mfa_enabled? : boolean,
  has_password? : boolean,
  has_seen_notifications? : boolean,
  has_shopping_showcase? : boolean,
  has_showcase? : boolean,
  id? : string,
  image_large_url? : string,
  image_medium_url? : string,
  image_small_url? : string,
  image_xlarge_url? : string,
  implicitly_followed_by_me? : boolean,
  impressum_url? : ?string,
  indexed? : boolean,
  interest_following_count? : number,
  ip_country? : ?string,
  is_any_website_verified? : boolean,
  is_default_image? : boolean,
  is_eligible_for_shop_tab? : boolean,
  is_employee? : boolean,
  is_geo_eligible_for_creator_messaging? : boolean,
  is_high_risk? : boolean,
  is_known_facebook_user? : boolean,
  is_partner? : boolean,
  is_primary_website_verified? : boolean,
  is_tastemaker? : boolean,
  is_third_party_ads_enabled? : boolean,
  is_verified_merchant? : boolean,
  is_write_banned? : boolean,
  joined_communities_count? : number,
  last_login_country? : ?string,
  last_name? : ?string,
  last_pin_done_time? : ?string,
  last_pin_like_time? : ?string,
  last_pin_save_time? : ?string,
  like_count? : number,
  listed_website_url? : ?string,
  locale? : ?string,
  location? : ?string,
  login_state? : ?number,
  merchant_id? : string,
  mfa_backup_codes? : | number[]
    | string[]
    | {| [key : string] : mixed |}[]
    | boolean[]
    | number[]
    | mixed[][],
  most_recent_board_sort_order? : string,
  nags? : | number[]
    | string[]
    | {| [key : string] : mixed |}[]
    | boolean[]
    | number[]
    | mixed[][],
  native_pin_count? : number,
  obfuscated_email? : string,
  personalize_from_offsite_browsing? : boolean,
  phone_country? : ?string,
  phone_number? : ?string,
  phone_number_end? : ?string,
  phone_number_without_country? : ?string,
  pin_count? : number,
  pin_thumbnail_urls? : string[],
  pins_done_count? : number,
  ppa_merchant_id? : string,
  profile_cover_source? : ?string,
  profile_discovered_public? : boolean,
  profile_reach? : ?number,
  profile_url? : string,
  push_package_user_id? : string,
  recent_pin_images? : ?{| [key : string] : mixed |},
  recommendation_reason? : ?string,
  resurrection_info? : ?{| [key : string] : mixed |},
  scheduled_pin_count? : number,
  secret_board_count? : number,
  secret_boards_remaining? : number,
  should_show_homefeed_ads? : boolean,
  show_creator_profile? : boolean,
  show_discovered_feed? : boolean,
  show_engagement_tab? : boolean,
  show_impressum? : boolean,
  storefront_management_enabled? : boolean,
  storefront_search_enabled? : boolean,
  story_pin_count? : number,
  tag? : ?string,
  third_party_ad_unit_id? : string,
  third_party_ads_config? : {| [key : string] : mixed |},
  third_party_app_id? : string,
  third_party_marketing_tracking_enabled? : boolean,
  triggerable_experiments? : {| [key : string] : mixed |},
  twitter_publish_enabled? : boolean,
  twitter_url? : ?string,
  type? : string,
  unverified_phone_country? : ?string,
  unverified_phone_number? : ?string,
  unverified_phone_number_without_country? : ?string,
  user_following_count? : number,
  user_recommendation_reason? : ?{| [key : string] : mixed |},
  username? : string,
  usmstate? : string,
  verified_domains? : string[],
  verified_identity? : ?{| [key : string] : mixed |},
  verified_user_websites? : string[],
  video_pin_count? : number,
  video_upload_allowed? : boolean,
  video_views? : number,
  website_url? : ?string,
|};
export type UserDetailed = {|
  about? : string,
  active? : boolean,
  blocked_by_me? : boolean,
  board_count? : number,
  canonical_merchant_domain? : ?string,
  commerce_module_data? : ?{| [key : string] : mixed |},
  created_at? : string,
  debug? : {| [key : string] : mixed |},
  domain_url? : ?string,
  domain_verified? : boolean,
  explicitly_followed_by_me? : boolean,
  first_name? : ?string,
  followed_by_me? : boolean,
  follower_count? : number,
  following_count? : number,
  full_name? : string,
  gender? : string,
  group_board_count? : number,
  has_custom_board_sorting_order? : boolean,
  id? : string,
  image_large_url? : string,
  image_medium_url? : string,
  image_small_url? : string,
  image_xlarge_url? : string,
  implicitly_followed_by_me? : boolean,
  impressum_url? : ?string,
  indexed? : boolean,
  is_any_website_verified? : boolean,
  is_default_image? : boolean,
  is_geo_eligible_for_creator_messaging? : boolean,
  is_partner? : boolean,
  is_primary_website_verified? : boolean,
  is_verified_merchant? : boolean,
  last_login_country? : ?string,
  last_name? : ?string,
  last_pin_like_time? : ?string,
  last_pin_save_time? : ?string,
  like_count? : number,
  listed_website_url? : ?string,
  location? : ?string,
  merchant_id? : string,
  native_pin_count? : number,
  obfuscated_email? : string,
  pin_count? : number,
  pin_thumbnail_urls? : string[],
  pins_done_count? : number,
  profile_cover_source? : ?string,
  profile_discovered_public? : boolean,
  profile_reach? : ?number,
  recent_pin_images? : ?{| [key : string] : mixed |},
  recommendation_reason? : ?string,
  show_creator_profile? : boolean,
  show_discovered_feed? : boolean,
  show_impressum? : boolean,
  tag? : ?string,
  type? : string,
  user_following_count? : number,
  user_recommendation_reason? : ?{| [key : string] : mixed |},
  username? : string,
  verified_domains? : string[],
  verified_identity? : ?{| [key : string] : mixed |},
  verified_user_websites? : string[],
  website_url? : ?string,
|};
export type UserSummary = {|
  first_name? : ?string,
  full_name? : string,
  gender? : string,
  id? : string,
  image_large_url? : string,
  image_medium_url? : string,
  image_small_url? : string,
  image_xlarge_url? : string,
  last_name? : ?string,
  type? : string,
  username? : string,
|};
export type add_fields = string[];
export type base_scheme = "http" | "https";
export type fields = string[];
export type render_style = "detailed" | "summary" | "all_fields";
